### ISSUE TITLE
希望可以编译一份linux版本的

### ISSUE THREAD

**Issue by zhenruyan** [cherryljr/PanDownload#11]
谢谢

**Comment by LarenDorr** [comment]
同求！！

**Comment by abcfy2** [comment]
同求这个，能支持下wine也行

**Comment by kmahyyg** [comment]
CROSSOVER运行出现严重内存泄漏

-------- Original Message --------

**Comment by zhenruyan** [comment]
命令行版的有一个项目很类似 有linux版的  .  =  .  不过还是gui更爽一点

**Comment by huangya90** [comment]
同求．ｔｈａｎｋｓ

**Comment by mzkingk** [comment]
同求linux版，或者优化一下对wine的支持也可以

**Comment by windmaple** [comment]
+1 求linux/mac版本

**Comment by ZeroOut** [comment]
谢谢，同求

**Comment by sudo0m** [comment]
求linux版本

**Comment by abcfy2** [comment]
找到了一个wine的方案，各位可以参考:

意外发现PanDownload在WineHQ是有测试的： https://appdb.winehq.org/objectManager.php?sClass=version&iId=38036

而这个也给出了方案(ie8在64位环境下装不了，但是不影响)，使用最新稳定版本的wine和winetricks:

1. 使用`winestricks`安装一些必要的wine组件

    winetricks winhttp msscript win7

1. 打开 `PanDownload`，账号登录使用扫码登录，因为用户名密码是肯定登录不了的，会超时卡住。扫码不一定非要用百度网盘的app，用微信或者浏览器也可以
1. 扫码登录之后页面不会跳转，点击下方的`登录成功未跳转点击此处`
1. 会有红色报错，找不到bcttoken什么的错误，不管，关闭这个页面，再点击一次登录，会发现能看到百度网盘的网页界面了，稍等一会或者再次关闭重新点击登录就可以了

**Comment by NebulaNeko** [comment]
https://aur.archlinux.org/packages/pandownload-bin/

**Comment by Hemingway2003** [comment]
> 找到了一个wine的方案，各位可以参考:
> 
> 意外发现PanDownload在WineHQ是有测试的： https://appdb.winehq.org/objectManager.php?sClass=version&iId=38036
> 
> 而这个也给出了方案(ie8在64位环境下装不了，但是不影响)，使用最新稳定版本的wine和winetricks:
> 
> 1. 使用`winestricks`安装一些必要的wine组件
>    ```shell
>    # WineHQ的评测页面写了一堆要装的组件，经过我测试只需要这一个就可以正常运行PanDownload
>    winetricks msscript
>    ```
> 2. 打开 `PanDownload`，账号登录使用扫码登录，因为用户名密码是肯定登录不了的，会超时卡住。扫码不一定非要用百度网盘的app，用微信或者浏览器也可以
> 3. 扫码登录之后页面不会跳转，点击下方的`登录成功未跳转点击此处`
> 4. 会有红色报错，获取bdstoken失败什么的错误，不管，关闭这个页面，再点击一次登录，会发现会卡在百度网盘登录进去后的页面，也刷不出来列表
> 5. 再次点一下下方的`登录成功未跳转点击此处`，会发现已经可以成功加载自己的百度网盘列表页了。之后就可以正常使用了
> 
> 特别注意不要选择最小化到托盘，会无法唤醒，怎么点托盘图标都没反应，右键菜单也无法呼出，至少我的DE环境是这样的，不知道其他DE环境是否OK

——————————————————————————
经过测试是可以的，但是不需要这么麻烦，直接使用下方的cookie登录就好，一次通过，另外安装msscript之前需要安装cabextract，debian下使用apt install命令，另外我是xfce环境，可以最小化

**Comment by VergeDX** [comment]
wine 登陆账号的话，我根据报错安装了 wine-gecko，然后 web 正常
