### ISSUE TITLE
这个项目使用了 GPL-2.0 的 aria2，但没有发布源代码

### ISSUE THREAD

**Issue by Menci** [cherryljr/PanDownload#15]
https://github.com/aria2/aria2/blob/master/COPYING

希望作者能给个回复

**Comment by cherryljr** [comment]
Sry, I'm not the major developer. 
I took part in the project half year ago, but now it's developed by my friends .
This project isn't open source currently...(but won't be forever)
I'll talk with them about this later, thks

**Comment by itviewer** [comment]
你们这帮脑残的智障，有何企图，违反了哪门子gpl，用aria是用的它的rpc接口，又没修改它源码，伸手要东西还这么牛逼，操，看不惯了

**Comment by huclengyue** [comment]
在中国这不都是常态吗。。之前的SSR还不是一样，不开源
