### ISSUE TITLE
给那些伸手要源码的

### ISSUE THREAD

**Issue by itviewer** [cherryljr/PanDownload#16]
1. 软件是否违反GPL协议
理论没有，也没必要违反。aria2的使用是通过其提供的json-rpc接口，其它GUI软件不需要修改其源码，aria2在Windows上发布是单一编译好的静态文件，其它软件也不会去静态链接它，从源码和接口调用层面不会产生gpl及lgpl感染问题。
目前我不确定仅仅在软件中包含GPL的软件组件是否违反GPL，之前看PanDownload应该是在第一次启动时释放aria2软件，如果是打包方式，改为第一次启动时直接通过网络下载则可彻底避免争议。

**不是所有使用了GPL软件的软件都会受感染，否则谷歌折腾安卓在Linux内核上建立HAL层是在瞎忙活了**
GPL的本质是保证你修改了源码别人也能修改，那些说没有包含一份GPL协议文档，没有提供aria2源码位置的就违反了GPL的，我不跟你抬杠。

2. 目前软件不可能在Linux和mac上编译
软件使用了duilib这个界面库，这个库依赖Windows api，不是跨平台的，不可能在Linux和mac上编译
3. 如何自己折腾aria界面

- 去读读aria2的文档，知道啥是个json-rpc接口。
- 了解个抓包工具，学会查看PanDownload调用了哪些api

你跑来github哔哔，我假设你是个写代码的，基本东西没搞清楚，张嘴就要代码，还这么霸气，不丢人么。

**Comment by Cologler** [comment]
不是这样的吧。

PanDownload 不管是将 aria2 打包进 exe 资源集还是第一次启动通过网络下载，都属于二次分发，都要开源的。

https://aria2.github.io/ 最底下有写：

> you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

https://github.com/aria2/aria2/blob/master/COPYING#L33-L37 也有写：

> For example, if you distribute copies of such a program, whether
gratis or for a fee, you must give the recipients all the rights that
you have.  You must make sure that they, too, receive or can get the
source code.  And you must show them these terms so they know their
rights.

正确的做法是第一次打开，打开浏览器，让用户自己去下载 aria2。

**Comment by itviewer** [comment]
看不懂别瞎哔哔

**Comment by Cologler** [comment]
小朋友真可怕，不过一看你的 repo 就知道你是怎样的伸手党了。

**Comment by kmahyyg** [comment]
@Cologler Thanks.
@itviewer Blocked.

Strongly suggest that the repository's maintainer close this issue. Thanks for your hard work.

**Comment by cpdyj** [comment]
这个怎么说呢，@Cologler aria2下方写的内容是针对Aria2的，如果作者修改了Aria2的源码，他的确应当开源，不过看起来并没有，你可以从原来的地方获得对应的Aria2的源码。至于PanDownload其他部分，似乎并不被GPL许可证污染。

**Comment by Cologler** [comment]
@cpdyj 'you can redistribute it and/or modify it' 中你只看到了 and 而忽视了 or

**Comment by cpdyj** [comment]
@Cologler ok，严格说确实如此，不过那样作者最多有义务提供Aria2的源码，emmm我实在没看出有多大意义。

**Comment by Cologler** [comment]
@cpdyj GPL 感染衍生程序，得看衍生程序的定义了（那一节我也看得稀里糊涂的）。如果 PanDownload 符合衍生程序的定义，那 PanDownload 本身也被要求开源。

**Comment by cpdyj** [comment]
@Cologler 说实话那一段确实稀里糊涂，感觉他们就不想定义的太清楚······我就理解成进程\地址空间隔离了。。。
