### ISSUE TITLE
软件暂停使用？？？

### ISSUE THREAD

**Issue by BILLYx1120** [cherryljr/PanDownload#17]
今天打开给我弹了个软件暂停使用然后闪退了...是被封了吗

**Comment by v1-hermit** [comment]
被起诉了吗？

**Comment by orrzz** [comment]
百毒这是要出手了吗？

**Comment by cherryljr** [comment]
统一回复：
近日起，百度进行了一系列的打击措施，使用第三方下载器有可能导致账号下载功能被禁用。
因此已紧急关停软件，防止用户账户受到影响。

**Comment by snowcity-cn** [comment]
谁牟他利了，是作者自己想牟利吧，隔三岔五搞这样的事

**Comment by G0510OLD** [comment]
你可以去淘宝上看看

**Comment by G0510OLD** [comment]
@snow212-cn 你这么说真的挺可笑的，你去淘宝上看过吗？
