### ISSUE TITLE
感谢作者曾经提供了这么好的下载器！

### ISSUE THREAD

**Issue by Mustela-sibirica** [cherryljr/PanDownload#19]
希望能再次遇见你！

**Comment by shuye02** [comment]
@Mustela-sibirica 很好奇发生了什么。。。很久不用了今天打开突然就发现软件暂停使用。。。

**Comment by Mustela-sibirica** [comment]
百度加大了破解软件的打击力度，用破解会封号，为了防止不明真相群众被封号，所以关闭了软件。

发送自 Windows 10 版邮件应用

发件人: Ye Shu
发送时间: 2018年1月20日 19:30
收件人: cherryljr/PanDownload
抄送: Mustela-sibirica; Mention
主题: Re: [cherryljr/PanDownload] 感谢作者曾经提供了这么好的下载器！ (#19)

@Mustela-sibirica 很好奇发生了什么。。。很久不用了今天打开突然就发现软件暂停使用。。。

**Comment by liarchgh** [comment]
感谢~~
