### ISSUE TITLE
已经暂停使用了么

### ISSUE THREAD

**Issue by admxj** [cherryljr/PanDownload#22]
刚刚打开提示 软件软件暂停使用

**Comment by cherryljr** [comment]
请参见 README 文件

**Comment by YoungWilliamZ** [comment]
抱着试试的额想法更新之后又能用了

**Comment by YoungWilliamZ** [comment]
同时有个脑洞分享下：可以先分享再获取下载链接，这样原来分享的账户应该就不会出事了吧

**Comment by guolei329** [comment]
更新后一直卡在了分配空间，有一样遇到这个情况的吗

**Comment by cherryljr** [comment]
不好意思，没有遇到这个问题呢...

方便具体描述一下吗



________________________________
发件人: Lei Guo <notifications@github.com>
发送时间: 2018年2月19日 5:02
收件人: cherryljr/PanDownload
抄送: cherryljr; Comment
主题: Re: [cherryljr/PanDownload] 已经暂停使用了么 (#22)


更新后一直卡在了分配空间，有一样遇到这个情况的吗

―

**Comment by guolei329** [comment]
@cherryljr Hi! 只是因为我下载的文件有点太大了。因为之前没有这个分配空间，所以以为是bug。
