### ISSUE TITLE
PanDownload 违反了GPL条款，侵犯了 aria2 版权

### ISSUE THREAD

**Issue by sdfww** [cherryljr/PanDownload#32]
PanDownload 使用了修改的 aria2，但其没有发布修改后的 aria2 的源代码，这违反了GPL许可！

这里仅指 aria2 本身，而非 Pandownload。但仅此，也理应发布修改后的 aria2 的源代码。

**Comment by hugetiny** [comment]
道德红卫兵真多

**Comment by sdfww** [comment]
红卫兵保护的你这样的流氓土匪才对
